---
apiVersion: v1
kind: ConfigMap
metadata:
  name: truecall-nb
  namespace: applications
data:
  truecall.yaml: |
    min_version: "5.17.1"
    description: Workload to test `truecall_h3_10` and `truecall_h3_8` tables with partitions, clusters, and data fields.

    scenarios:
      default:
        schema: run driver=cql tags==block:schema threads==1 cycles==UNDEF
        rampup: run driver=cql tags==block:rampup cycles===TEMPLATE(rampup-cycles,50000000) threads=auto
        main: run driver=cql tags==block:main-*.* cycles===TEMPLATE(main-cycles,50000000) threads=auto
      astra:
        schema: run driver=cql tags==block:schema_astra threads==1 cycles==UNDEF
        rampup: run driver=cql tags==block:rampup cycles===TEMPLATE(rampup-cycles,50000000) threads=auto
        main: run driver=cql tags==block:main-*.* cycles===TEMPLATE(main-cycles,50000000) threads=auto
      basic_check:
        schema: run driver=cql tags==block:schema threads==1 cycles==UNDEF
        rampup: run driver=cql tags==block:rampup cycles===TEMPLATE(rampup-cycles,10) threads=auto
        main: run driver=cql tags==block:main-*.* cycles===TEMPLATE(main-cycles,10) threads=auto

    bindings:
      # For ramp-up and verify
      h3_10_value: Uniform(1,100000000); ToString() -> String
      h3_8_value: Uniform(1,8000000); ToString() -> String
      event_time: StartingEpochMillis('2022-12-21 05:00:00'); ToJavaInstant();
      avg_cqi: Uniform(0.0, 100.0) -> double; ToFloat()
      avg_rsrp_dbm: Uniform(-130.0, -30.0) -> double; ToFloat()
      avg_rsrq_db: Uniform(-20.0, 0.0) -> double; ToFloat()
      avg_throughput_downlink_volume_kbytes: Uniform(0.0, 102400.0) -> double; ToFloat()
      avg_throughput_uplink_volume_kbytes: Uniform(0.0, 102400.0) -> double; ToFloat()
      avg_ul_sinr: Uniform(-10.0, 30.0) -> double; ToFloat()
      distinct_imsi_count: Uniform(1, 1000) -> int
      records_count: Uniform(1, 100000) -> int
      limit: Uniform(1, 10) -> int

    blocks:
      schema:
        params:
          prepared: false
        ops:
          create_keyspace: |
            CREATE KEYSPACE IF NOT EXISTS gkiv_cnsmap_prod
            WITH replication = {'class': 'NetworkTopologyStrategy', 'dc-1': '3'}
            AND durable_writes = true;
          create_table_truecall_h3_10: |
            CREATE TABLE IF NOT EXISTS gkiv_cnsmap_prod.truecall_h3_10 (
              h3_10 text,
              event_time timestamp,
              avg_cqi float,
              avg_rsrp_dbm float,
              avg_rsrq_db float,
              avg_throughput_downlink_volume_kbytes float,
              avg_throughput_uplink_volume_kbytes float,
              avg_ul_sinr float,
              distinct_imsi_count int,
              records_count int,
              PRIMARY KEY (h3_10, event_time)
            ) WITH CLUSTERING ORDER BY (event_time ASC)
              AND additional_write_policy = '99PERCENTILE'
              AND bloom_filter_fp_chance = 0.01
              AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
              AND comment = ''
              AND compaction = {'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
              AND compression = {'chunk_length_in_kb': '4', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
              AND crc_check_chance = 1.0
              AND default_time_to_live = 172800
              AND gc_grace_seconds = 0
              AND max_index_interval = 2048
              AND memtable_flush_period_in_ms = 0
              AND min_index_interval = 128
              AND read_repair = 'BLOCKING'
              AND speculative_retry = '99PERCENTILE';
          create_table_truecall_h3_8: |
            CREATE TABLE IF NOT EXISTS gkiv_cnsmap_prod.truecall_h3_8 (
              h3_8 text,
              event_time timestamp,
              avg_cqi float,
              avg_rsrp_dbm float,
              avg_rsrq_db float,
              avg_throughput_downlink_volume_kbytes float,
              avg_throughput_uplink_volume_kbytes float,
              avg_ul_sinr float,
              distinct_imsi_count int,
              records_count int,
              PRIMARY KEY (h3_8, event_time)
            ) WITH CLUSTERING ORDER BY (event_time ASC)
              AND additional_write_policy = '99PERCENTILE'
              AND bloom_filter_fp_chance = 0.01
              AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
              AND comment = ''
              AND compaction = {'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
              AND compression = {'chunk_length_in_kb': '4', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
              AND crc_check_chance = 1.0
              AND default_time_to_live = 172800
              AND gc_grace_seconds = 0
              AND max_index_interval = 2048
              AND memtable_flush_period_in_ms = 0
              AND min_index_interval = 128
              AND read_repair = 'BLOCKING'
              AND speculative_retry = '99PERCENTILE';


      rampup:
        params:
          cl: LOCAL_QUORUM
        ops:
          rampup_insert_h3_10: |
            INSERT INTO gkiv_cnsmap_prod.truecall_h3_10 (h3_10, event_time, avg_cqi, avg_rsrp_dbm, avg_rsrq_db, avg_throughput_downlink_volume_kbytes, avg_throughput_uplink_volume_kbytes, avg_ul_sinr, distinct_imsi_count, records_count)
            values ({h3_10_value}, {event_time}, {avg_cqi}, {avg_rsrp_dbm}, {avg_rsrq_db}, {avg_throughput_downlink_volume_kbytes}, {avg_throughput_uplink_volume_kbytes}, {avg_ul_sinr}, {distinct_imsi_count}, {records_count});
          rampup_insert_h3_8: |
            INSERT INTO gkiv_cnsmap_prod.truecall_h3_8 (h3_8, event_time, avg_cqi, avg_rsrp_dbm, avg_rsrq_db, avg_throughput_downlink_volume_kbytes, avg_throughput_uplink_volume_kbytes, avg_ul_sinr, distinct_imsi_count, records_count)
            values ({h3_8_value}, {event_time}, {avg_cqi}, {avg_rsrp_dbm}, {avg_rsrq_db}, {avg_throughput_downlink_volume_kbytes}, {avg_throughput_uplink_volume_kbytes}, {avg_ul_sinr}, {distinct_imsi_count}, {records_count});

      main_read:
        params:
          ratio: 5
          cl: LOCAL_QUORUM
        ops:
          main_select_h3_10: |
            SELECT * FROM gkiv_cnsmap_prod.truecall_h3_10 WHERE h3_10={h3_value} LIMIT {limit};
          main_select_h3_8: |
            SELECT * FROM gkiv_cnsmap_prod.truecall_h3_8 WHERE h3_8={h3_value} LIMIT {limit};

      main_write:
        params:
          ratio: 5
          cl: LOCAL_QUORUM
        ops:
          main_write_h3_10: |
            INSERT INTO gkiv_cnsmap_prod.truecall_h3_10 (h3_10, event_time, avg_cqi, avg_rsrp_dbm, avg_rsrq_db, avg_throughput_downlink_volume_kbytes, avg_throughput_uplink_volume_kbytes, avg_ul_sinr, distinct_imsi_count, records_count)
            VALUES ({h3_10_value}, {event_time}, {avg_cqi}, {avg_rsrp_dbm}, {avg_rsrq_db}, {avg_throughput_downlink_volume_kbytes}, {avg_throughput_uplink_volume_kbytes}, {avg_ul_sinr}, {distinct_imsi_count}, {records_count});
          main_write_h3_8: |
            INSERT INTO gkiv_cnsmap_prod.truecall_h3_8 (h3_8, event_time, avg_cqi, avg_rsrp_dbm, avg_rsrq_db, avg_throughput_downlink_volume_kbytes, avg_throughput_uplink_volume_kbytes, avg_ul_sinr, distinct_imsi_count, records_count)
            VALUES ({h3_8_value}, {event_time}, {avg_cqi}, {avg_rsrp_dbm}, {avg_rsrq_db}, {avg_throughput_downlink_volume_kbytes}, {avg_throughput_uplink_volume_kbytes}, {avg_ul_sinr}, {distinct_imsi_count}, {records_count});

---
apiVersion: batch/v1
kind: Job
metadata:
  name: truecall-nb
  namespace: applications
spec:
  template:
    spec:
      containers:
        - name: nb
          image: nosqlbench/nosqlbench:latest
          env:
            - name: JAVA_OPTS
              value: --enable-preview
          args:
            - workloads/truecall

            - default.schema
            - default.rampup
            # - ramp
            # - ramp-cycles=1000000
            # - main
            # - main-cycles=1000000

            - cyclerate=800
            - stride=5
            - threads=2

            - host=hcd-dc-1-service.demo-z5348r3n.svc.cluster.local

            - username=hcd-superuser
            - password=yourPassword
            - localdc=dc-1
            - --progress
            - console:1s
            - --report-summary-to
            - stdout:60
            - errors=counter
          resources:
            requests:
              cpu: "1"
          volumeMounts:
            - name: workload
              mountPath: /workloads
            - name: logs
              mountPath: /logs
            - name: state
              mountPath: /.nosqlbench
          imagePullPolicy: Always
      volumes:
        - name: workload
          configMap:
            name: truecall-nb
        - name: logs
          emptyDir: {}
        - name: state
          emptyDir: {}
      restartPolicy: Never
  completions: 2
  parallelism: 1
  completionMode: Indexed
  backoffLimit: 1
